name: Events Pipeline
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  Pre_Test:
    runs-on: ubuntu_latest
    steps:
      - name: Print Event
        run: echo "${{ toJSON(github.event) }}"
  Test:
  runs-on: ubuntu_latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Run Test
      run: |
        javac Substraction.java
        java AddiSubstractiontion

        echo "Test Passed Successfully"
    